### PR TITLE
trpc-v10 support

### LINKED ISSUE #24: Moving to trpc-v10
Currently, trpc-playground won't work if you are using a trpc-v10 server. I created this issue to discuss on how/when we should convert to using trpc-v10.

I think it would be better if we moved to a structure for writing queries like this:
```typescript
await trpc.users.byId.query({ userId })
```
Instead of
```typescript
await query("user.byId", { userId })
```

What do you think about this? Should we wait until v10 is released?
I am happy to work on this.

### PR DESCRIPTION
**Pull request by MatsDK**
closes #24

This PR adds support for using trpc-v10 routers and gives users the ability to call queries with a proxy-structure.
```typescript
await trpc.users.byId.query({ userId })
```

I upgraded all the versions of `@trpc/server` and `@trpc/client` to `10.0.0-proxy-alpha.76`, is this correct?

### CODE REVIEW

**Comment by MatsDK** [comment]
Currently I am just merging multiple input-parsers, but I don't know if this the correct way to handle multiple input-parsers in v10.
https://github.com/MatsDK/trpc-playground/blob/b7c2037f38eb3d41b456c24db126458eece5f564/packages/trpc-playground/src/zod-resolve-types.ts#L44-L54

**Comment by sachinraja** [comment]
Thanks for doing this! I invited you as a collaborator on the repository. Merging multiple input parsers is fine!

**Comment by sachinraja** [comment]
Thanks, this is amazing work!

**Comment by sachinraja** [comment]
available at `1.0.0-next.0`

**Pull request merged**
